### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by otakbeku** [saungkertas/data_lineage_demo#1]
Hi mas Syarif!

I saw your presentation on Pycon 2019 last Saturday and I was amaze by you introduction to data lineage. Luckily, you put your codes in Github so I can try too. Thanks a lot for this. Anyways I have a question. Does the dataset is open? I try to find it from Google about public dataset and I can't find any single one. My guess is the imdb is from the [kaggle](https://www.kaggle.com/iarunava/imdb-movie-reviews-dataset). I appreciate any time you can give me the answer. Thank you very much,

**Comment by saungkertas** [comment]
Hi,

Yes, it's a public datasets.
you can access it here:
https://relational.fit.cvut.cz/dataset/imdb

https://relational.fit.cvut.cz/dataset/Financial

Thanks
-Syarif-

**Comment by otakbeku** [comment]
Thank you so much for you help!

I would like to open other issues but I'll try by myself first. This example really helps me to learn about dbt and apache beam
